### PR TITLE
AK: Enable format string checking in Clang builds

### PR DESCRIPTION
**Pull request by BertalanD**
Format string checking was disabled in Clang-based builds due to a compiler bug: https://github.com/llvm/llvm-project/issues/51182. Now that the requirement has been raised to Clang 17, that is no longer necessary.

This has been tested to work correctly with Apple Clang 15.0.0 (which is the *least modern* supported compiler), as well as CLion 2024.1's bundled Clangd.

### CODE REVIEW

**Comment by BertalanD** [comment]
[This](https://github.com/SerenityOS/serenity/actions/runs/9172897455/job/25220419847?pr=24400#step:10:1028) is *unexpected*, to say the least:

```
sql.cpp:(.text._ZN2AK6Format6Detail19CheckedFormatStringIJNS_10ByteStringEEE34check_format_parameter_consistencyILm16ELm1EEEbRAT__Kc[_ZN2AK6Format6Detail19CheckedFormatStringIJNS_10ByteStringEEE34check_format_parameter_consistencyILm16ELm1EEEbRAT__Kc]+0xfc): undefined reference to `auto AK::Format::Detail::count_fmt_params<16ul>(char const (&) [16ul])'
```

**Comment by trflynn89** [comment]
That workaround looks fine to me if you want to just fixup the commit message

**Review by ADKaster — APPROVED** [review]
