### ISSUE TITLE
Build on Macbook pro arm m1 failed 

### ISSUE THREAD

**Issue by lixiao189** [SerenityOS/serenity#16969]
At first, I run `./Meta/serenity.sh rebuild-toolchain aarch64 Clang` command to build arm Clang tool chain, it works perfect.
However, when I run ` ./Meta/serenity.sh run aarch64 Clang` command, it failed when performing build step for 'lagom'.

<img width="1572" alt="image" src="https://user-images.githubusercontent.com/44799572/212009326-3e0396bd-e8dc-4758-b162-b0210fe0c8fa.png">

This is the whole output:

```
[0/10] Performing build step for 'lagom'
[1/38] Linking CXX executable Tools/CodeGenerators/LibLocale/GenerateNumberFormatData
FAILED: Tools/CodeGenerators/LibLocale/GenerateNumberFormatData 
: && /opt/homebrew/opt/llvm/bin/clang++ -arch arm64 -isysroot /Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  Tools/CodeGenerators/LibLocale/CMakeFiles/GenerateNumberFormatData.dir/GenerateNumberFormatData.cpp.o -o Tools/CodeGenerators/LibLocale/GenerateNumberFormatData  -Wl,-rpath,/Users/node/Developer/C/serenity/Build/lagom/Userland/Libraries/LibCore  Userland/Libraries/LibMain/liblagom-main.a  Userland/Libraries/LibCore/liblagom-core.0.0.0.dylib && :
ld: warning: ignoring file Userland/Libraries/LibMain/liblagom-main.a, building for macOS-arm64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: serenity_main(Main::Arguments))
ld: symbol(s) not found for architecture arm64
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
[2/38] Linking CXX executable Tools/CodeGenerators/LibTimeZone/GenerateTimeZoneData
FAILED: Tools/CodeGenerators/LibTimeZone/GenerateTimeZoneData 
: && /opt/homebrew/opt/llvm/bin/clang++ -arch arm64 -isysroot /Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  Tools/CodeGenerators/LibTimeZone/CMakeFiles/GenerateTimeZoneData.dir/GenerateTimeZoneData.cpp.o -o Tools/CodeGenerators/LibTimeZone/GenerateTimeZoneData  -Wl,-rpath,/Users/node/Developer/C/serenity/Build/lagom/Userland/Libraries/LibCore  Userland/Libraries/LibMain/liblagom-main.a  Userland/Libraries/LibCore/liblagom-core.0.0.0.dylib && :
ld: warning: ignoring file Userland/Libraries/LibMain/liblagom-main.a, building for macOS-arm64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: serenity_main(Main::Arguments))
ld: symbol(s) not found for architecture arm64
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
[3/38] Linking CXX executable Tools/CodeGenerators/LibEDID/GeneratePnpIDsData
FAILED: Tools/CodeGenerators/LibEDID/GeneratePnpIDsData 
: && /opt/homebrew/opt/llvm/bin/clang++ -arch arm64 -isysroot /Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  Tools/CodeGenerators/LibEDID/CMakeFiles/GeneratePnpIDsData.dir/GeneratePnpIDs.cpp.o -o Tools/CodeGenerators/LibEDID/GeneratePnpIDsData  -Wl,-rpath,/Users/node/Developer/C/serenity/Build/lagom/Userland/Libraries/LibCore  Userland/Libraries/LibMain/liblagom-main.a  Userland/Libraries/LibCore/liblagom-core.0.0.0.dylib && :
ld: warning: ignoring file Userland/Libraries/LibMain/liblagom-main.a, building for macOS-arm64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: serenity_main(Main::Arguments))
ld: symbol(s) not found for architecture arm64
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
[4/38] Linking CXX executable Tools/CodeGenerators/IPCCompiler/IPCCompiler
FAILED: Tools/CodeGenerators/IPCCompiler/IPCCompiler 
: && /opt/homebrew/opt/llvm/bin/clang++ -arch arm64 -isysroot /Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  Tools/CodeGenerators/IPCCompiler/CMakeFiles/IPCCompiler.dir/main.cpp.o -o Tools/CodeGenerators/IPCCompiler/IPCCompiler  -Wl,-rpath,/Users/node/Developer/C/serenity/Build/lagom/Userland/Libraries/LibCore  Userland/Libraries/LibMain/liblagom-main.a  Userland/Libraries/LibCore/liblagom-core.0.0.0.dylib && :
ld: warning: ignoring file Userland/Libraries/LibMain/liblagom-main.a, building for macOS-arm64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: serenity_main(Main::Arguments))
ld: symbol(s) not found for architecture arm64
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
[5/38] Linking CXX executable Tools/CodeGenerators/LibLocale/GenerateLocaleData
FAILED: Tools/CodeGenerators/LibLocale/GenerateLocaleData 
: && /opt/homebrew/opt/llvm/bin/clang++ -arch arm64 -isysroot /Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  Tools/CodeGenerators/LibLocale/CMakeFiles/GenerateLocaleData.dir/GenerateLocaleData.cpp.o -o Tools/CodeGenerators/LibLocale/GenerateLocaleData  -Wl,-rpath,/Users/node/Developer/C/serenity/Build/lagom/Userland/Libraries/LibCore  Userland/Libraries/LibMain/liblagom-main.a  Userland/Libraries/LibCore/liblagom-core.0.0.0.dylib && :
ld: warning: ignoring file Userland/Libraries/LibMain/liblagom-main.a, building for macOS-arm64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: serenity_main(Main::Arguments))
ld: symbol(s) not found for architecture arm64
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
[6/38] Linking CXX executable Tools/CodeGenerators/LibLocale/GenerateRelativeTimeFormatData
FAILED: Tools/CodeGenerators/LibLocale/GenerateRelativeTimeFormatData 
: && /opt/homebrew/opt/llvm/bin/clang++ -arch arm64 -isysroot /Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  Tools/CodeGenerators/LibLocale/CMakeFiles/GenerateRelativeTimeFormatData.dir/GenerateRelativeTimeFormatData.cpp.o -o Tools/CodeGenerators/LibLocale/GenerateRelativeTimeFormatData  -Wl,-rpath,/Users/node/Developer/C/serenity/Build/lagom/Userland/Libraries/LibCore  Userland/Libraries/LibMain/liblagom-main.a  Userland/Libraries/LibCore/liblagom-core.0.0.0.dylib && :
ld: warning: ignoring file Userland/Libraries/LibMain/liblagom-main.a, building for macOS-arm64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: serenity_main(Main::Arguments))
ld: symbol(s) not found for architecture arm64
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
[7/38] Linking CXX executable Tools/CodeGenerators/LibLocale/GeneratePluralRulesData
FAILED: Tools/CodeGenerators/LibLocale/GeneratePluralRulesData 
: && /opt/homebrew/opt/llvm/bin/clang++ -arch arm64 -isysroot /Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  Tools/CodeGenerators/LibLocale/CMakeFiles/GeneratePluralRulesData.dir/GeneratePluralRulesData.cpp.o -o Tools/CodeGenerators/LibLocale/GeneratePluralRulesData  -Wl,-rpath,/Users/node/Developer/C/serenity/Build/lagom/Userland/Libraries/LibCore  Userland/Libraries/LibMain/liblagom-main.a  Userland/Libraries/LibCore/liblagom-core.0.0.0.dylib && :
ld: warning: ignoring file Userland/Libraries/LibMain/liblagom-main.a, building for macOS-arm64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: serenity_main(Main::Arguments))
ld: symbol(s) not found for architecture arm64
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
[8/38] Linking CXX executable Tools/CodeGenerators/LibGL/GenerateGLAPIWrapper
FAILED: Tools/CodeGenerators/LibGL/GenerateGLAPIWrapper 
: && /opt/homebrew/opt/llvm/bin/clang++ -arch arm64 -isysroot /Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  Tools/CodeGenerators/LibGL/CMakeFiles/GenerateGLAPIWrapper.dir/GenerateGLAPIWrapper.cpp.o -o Tools/CodeGenerators/LibGL/GenerateGLAPIWrapper  -Wl,-rpath,/Users/node/Developer/C/serenity/Build/lagom/Userland/Libraries/LibCore  Userland/Libraries/LibMain/liblagom-main.a  Userland/Libraries/LibCore/liblagom-core.0.0.0.dylib && :
ld: warning: ignoring file Userland/Libraries/LibMain/liblagom-main.a, building for macOS-arm64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: serenity_main(Main::Arguments))
ld: symbol(s) not found for architecture arm64
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
FAILED: lagom-prefix/src/lagom-stamp/lagom-build /Users/node/Developer/C/serenity/Build/superbuild-aarch64clang/lagom-prefix/src/lagom-stamp/lagom-build 
cd /Users/node/Developer/C/serenity/Build/lagom && /opt/homebrew/Cellar/cmake/3.25.1/bin/cmake --build .
ninja: build stopped: subcommand failed.
```

This is the system info:
<img width="354" alt="Screenshot 2023-01-12 at 15 55 54" src="https://user-images.githubusercontent.com/44799572/212009839-076bba66-1769-490a-9a40-47a391dd9aff.png">

The clang I used to built the tool chain is clang 15 which installed by brew.

<img width="469" alt="image" src="https://user-images.githubusercontent.com/44799572/212010124-ebd31681-1550-466e-8cee-28e892f66d07.png">

**Comment by ADKaster** [comment]
A fresh build on my M2 Air seems to work with homebrew clang 15.0.6 and Xcode 14.2.0

```
[106/125] : && /opt/homebrew/opt/llvm/bin/clang++ -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  Tools/CodeGenerators/LibLocale/CMakeFiles/GenerateNumberFormatData.dir/GenerateNumberFormatData.cpp.o -o Tools/CodeGenerators/LibLocale/GenerateNumberFormatData  -Wl,-rpath,/Users/andrew/Source/serenity/Build/lagom-test/Userland/Libraries/LibCore  Userland/Libraries/LibMain/liblagom-main.a  Userland/Libraries/LibCore/liblagom-core.0.0.0.dylib && :
```

Using this exact command:
```
~/Source/serenity$ cmake -S Meta/Lagom -DCMAKE_CXX_COMPILER=$(brew --prefix llvm)/bin/clang++ -DCMAKE_C_COMPILER=$(brew --prefix llvm)/bin/clang -B Build/lagom-test -GNinja
-- The C compiler identification is Clang 15.0.6
-- The CXX compiler identification is Clang 15.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/homebrew/opt/llvm/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/homebrew/opt/llvm/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Removing outdated /Users/andrew/Source/serenity/Build/lagom-test/TZDB for version 2022g
-- Downloading file tzdb.tar.gz from https://data.iana.org/time-zones/releases/tzdata2022g.tar.gz
-- Extracting using cmake africa
-- Extracting using cmake antarctica
-- Extracting using cmake asia
-- Extracting using cmake australasia
-- Extracting using cmake backward
-- Extracting using cmake etcetera
-- Extracting using cmake europe
-- Extracting using cmake northamerica
-- Extracting using cmake southamerica
-- Extracting using cmake zone1970.tab
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/andrew/Source/serenity/Build/lagom-test
```
With `xcode-select -p` pointing to `/Applications/Xcode.app/Contents/Developer`

We define `main` in the static binary `liblagom-main.a` which gets linked into almost every binary in the Lagom build.
----

I would first verify that that library exists, and if not, do a clean build of serenity by first doing `rm -r serenity/Build` and then doing your `Meta/serenity.sh run aarch64 Clang` build again (do not remove the Toolchain/Local directory or run a `rebuild-toolchain`, the toolchain build is irrelevant to this issue.)

Do note that the aarch64 build is a tech demo at this point -- if you actually want to run the system you will need `./Meta/serenity.sh run x86_64 Clang`

Also note that the contribution guidelines ask to troubleshoot build issues in the #build-problems channel on our discord, so if the above steps don't improve anything please ask again there.

**Comment by lixiao189** [comment]
Thank you, I will have a try
