### ISSUE TITLE
Ports: Too many are broken!

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#18238]
Out of 285 ports, 9+0 are broken. Let's get these working again :D

I'll use this table to keep track of how far we've come. Table last updated: 2023-08-15

| Port | Status |
|------|--------|
| freedink | 💥 BROKEN: compilation error: invalid conversion from 'const char*' to 'char*' |
| frotz | 💥 BROKEN: bad sha256, ping @EWouters, handled in #18339 |
| gnuapl | 💥 BROKEN: Clash of definitions, redefines sysbeep: /home/user/serenity/Build/x86_64/Root/usr/include/unistd.h:38:13: `error: cast from 'TERMTYPE*' {aka 'termtype*'} to 'int' loses precision [-fpermissive]` |
| guile | #19855 💥 BROKEN: requires local installation of exact same version, and then fails to compile due to missing "csqrt" |
| nesalizer | :ear: :warning:  [choppy audio](https://github.com/SerenityOS/serenity/issues/18238#issuecomment-1652537621), partially fixed by #20391 ~~💥 BROKEN: Can't find SDL2/_real_SDL_config.h~~ |
| OpenJDK | 💥 BROKEN: See #18113 |
| p7zip | 💥 BROKEN: bad sha256, ping @timschumi and @cooljohnny3 |
| qt6-serenity |BROKEN: compilation error due to `GUI::Application`: `error: 'construct' is not a member of 'GUI::Application'` (See also #18241) |
| vlang | 💥 BROKEN: compilation error in the v language itself?! |
|------|--------|
| freeciv | 🩹 Fixed by #20309 ~~💥 BROKEN: bad sha256~~ |
| opentyrian-data | 🪦 REMOVED in #20048 ~~🤔 TOOHARD (needs a copy of the game, which I don't have, and begins with a `rm -v`, which fails)~~ |
| alpine | 🩹 Fixed by #19904 ~~💥 BROKEN: libtool version mismatch~~ |
| llvm | 🩹 Fixed by something, probably #18522 ~~💥 BROKEN: "Unable to determine platform"?~~ |
| boost | 🩹 Fixed by #19813 ~~🤔 TOOHARD (needs a special python version; compilation error with python3.11-dev)~~ |
| imagemagick | 🩹 Fixed by #19822 ~~💥 BROKEN: Tries to access files in the wrong directory~~ |
| ffmpeg |  🩹 Fixed by #19700 ~~💥 BROKEN: "relocation R_X86_64_PC32 against symbol `ff_pw_5` can not be used when making a shared object; recompile with -fPIC"~~ |
| nethack | 🩹 Fixed by #18779 ~~💥 BROKEN: compilation error in /usr/include/x86_64-linux-gnu/sys/cdefs.h:405:73: error: macro "__has_attribute" requires an identifier (code is `__glibc_has_attribute (__warn_unused_result__)`) handled in #18779~~ |
| | (Old fixes moved into the collapsible list below) |
|------|--------|
| file | ✅ WORKS (needs the EXACT SAME version installed) |
| mold | ✅ WORKS (needs some extra dependencies, and OOMs way too easily) |
| zig | ✅ WORKS (needs some extra dependencies, and OOMs way too easily) |

<details><summary>Ports that work perfectly fine</summary>

| Port | Status |
|------|--------|
| SDL_sound | 🩹 Fixed by … doing nothing? I don't understand. ~~💥 BROKEN: compilation error: unknown type name `'__EXPORT__'`~~ |
| SDL_sound | 🩹 Fixed by … doing nothing? I don't understand. ~~💥 BROKEN: only when compiling for gltron, it doesn't find libc.so, then link error undef ref to pow and floor o.O~~ |
|gltron | 🩹 Fixed by … doing nothing? I don't understand. ~~😭 BROKEN DEP (requires SDL_sound which is broken)~~ |
|gnuplot| 🩹 Fixed by … doing nothing? I don't understand. ~~💥 BROKEN: link error: undef ref to png_create_write_struct, FT_Init_FreeType, libiconv_open, and more~~|
| taskwarrior | 🩹 Fixed by … doing nothing? I don't understand. See also #18515 ~~💥 BROKEN: link error: undef ref to libintl_gettext~~ |
| lrzip | 🩹 Fixed by #18268 ~~💥 BROKEN: system `serenity` not recognized~~ |
| openrct2 | 🩹 Fixed by #18377 ~~💥 BROKEN: link error: undef ref to fnmatch, and nothing else~~ |
| fheroes2 | 🪦 REMOVED in #18254 ~~💥 BROKEN: in fheroes2-0.9.13/src/engine/serialize.h:329:24: "Unknown byte order"~~ |
| gnupg | 🩹 Fixed by https://github.com/SerenityOS/serenity/pull/18253 ~~😭 BROKEN DEP (requires libksba which is broken)~~ |
| libassuan | 🩹 Fixed by https://github.com/SerenityOS/serenity/pull/18253 ~~💥 BROKEN: link error: `undef ref to __environ_is_malloced, s_global_initializers_ran, _ctype_, __begin_atexit_locking, and more`~~ |
| libksba | 🩹 Fixed by https://github.com/SerenityOS/serenity/pull/18253 ~~💥 BROKEN: link error: undef ref to `__environ_is_malloced, s_global_initializers_ran, _ctype_, __begin_atexit_locking, and more`~~ |
| ntbtls | 🩹 Fixed by https://github.com/SerenityOS/serenity/pull/18253 ~~😭 BROKEN DEP (requires libksba which is broken)~~ |
| qt6-qt5compat | 🩹 Fixed by #18241 ~~😭 BROKEN DEP (requires qt6-qtbase which is broken)~~ |
| qt6-qtbase | 🩹 Fixed by #18241 ~~💥 BROKEN: doesn't find sys/ioctl_numbers.h, which seems to have moved to Kernel/API/Ioctl.h~~ |
| SDL2_sound | 🩹 Fixed by https://github.com/SerenityOS/serenity/pull/18246 ~~💥 BROKEN: patch does not apply, ping @Danik2343~~ |
| stpuzzles | 🩹 Fixed by https://github.com/SerenityPorts/stpuzzles/pull/7 ~~💥 BROKEN: compilation error around Ports/stpuzzles/stpuzzles-main/serenity.cpp:500~~ |
|------|--------|
| bass | ✅ WORKS (needs some extra dependencies) |
| bdwgc | ✅ WORKS (needs some extra dependencies) |
| composer | ✅ WORKS (needs some extra dependencies) |
| dos2unix | ✅ WORKS (needs some extra dependencies) |
| dosbox-staging | ✅ WORKS (needs some extra dependencies) |
| drascula | ✅ WORKS (needs some extra dependencies) |
| dreamweb | ✅ WORKS (needs some extra dependencies) |
| dungeonrush | ✅ WORKS (needs some extra dependencies) |
| ed | ✅ WORKS (needs some extra dependencies) |
| fontconfig | ✅ WORKS (needs some extra dependencies) |
| fotaq | ✅ WORKS (needs some extra dependencies) |
| gemrb | ✅ WORKS (needs some extra dependencies) |
| git | ✅ WORKS (needs some extra dependencies) |
| glib | ✅ WORKS (needs some extra dependencies) |
| gnucobol | ✅ WORKS (needs some extra dependencies) |
| griffon | ✅ WORKS (needs some extra dependencies) |
| halflife | ✅ WORKS (needs some extra dependencies) |
| jq | ✅ WORKS (needs some extra dependencies) |
| lite-xl | ✅ WORKS (needs some extra dependencies) |
| luarocks | ✅ WORKS (needs some extra dependencies) |
| lure | ✅ WORKS (needs some extra dependencies) |
| mc | ✅ WORKS (needs some extra dependencies) |
| mruby | ✅ WORKS (needs some extra dependencies) |
| mysthous | ✅ WORKS (needs some extra dependencies) |
| neofetch | ✅ WORKS (needs some extra dependencies) |
| ninja | ✅ WORKS (needs some extra dependencies) |
| nippon | ✅ WORKS (needs some extra dependencies) |
| OpenJDK | ✅ WORKS (needs some extra dependencies) |
| opfor | ✅ WORKS (needs some extra dependencies) |
| pacman | ✅ WORKS (needs some extra dependencies) |
| php | ✅ WORKS (needs some extra dependencies) |
| powdertoy | ✅ WORKS (needs some extra dependencies) |
| prboom-plus | ✅ WORKS (needs some extra dependencies) |
| python3 | ✅ WORKS (needs some extra dependencies) |
| qemu | ✅ WORKS (needs some extra dependencies) |
| quake3 | ✅ WORKS (needs some extra dependencies) |
| quake | ✅ WORKS (needs some extra dependencies) |
| RetroArch | ✅ WORKS (needs some extra dependencies) |
| scummvm | ✅ WORKS (needs some extra dependencies) |
| sfinx | ✅ WORKS (needs some extra dependencies) |
| soltys | ✅ WORKS (needs some extra dependencies) |
| VVVVVV | ✅ WORKS (needs some extra dependencies) |
| wayland | ✅ WORKS (needs some extra dependencies) |
| x264 | ✅ WORKS (needs some extra dependencies) |
| xash3d-fwgs | ✅ WORKS (needs some extra dependencies) |
|------|--------|
| aclock | ✅ WORKS (without special dependencies) |
| acpica-tools | ✅ WORKS (without special dependencies) |
| angband | ✅ WORKS (without special dependencies) |
| Another-World | ✅ WORKS (without special dependencies) |
| aria2 | ✅ WORKS (without special dependencies) |
| awk | ✅ WORKS (without special dependencies) |
| backward-cpp | ✅ WORKS (without special dependencies) |
| bash | ✅ WORKS (without special dependencies) |
| bc | ✅ WORKS (without special dependencies) |
| binutils | ✅ WORKS (without special dependencies) |
| bison | ✅ WORKS (without special dependencies) |
| bochs | ✅ WORKS (without special dependencies) |
| brogue | ✅ WORKS (without special dependencies) |
| byacc | ✅ WORKS (without special dependencies) |
| bzip2 | ✅ WORKS (without special dependencies) |
| bzip3 | ✅ WORKS (without special dependencies) |
| ca-certificates | ✅ WORKS (without special dependencies) |
| carl | ✅ WORKS (without special dependencies) |
| ccache | ✅ WORKS (without special dependencies) |
| cfunge | ✅ WORKS (without special dependencies) |
| chester | ✅ WORKS (without special dependencies) |
| citron | ✅ WORKS (without special dependencies) |
| ClassiCube | ✅ WORKS (without special dependencies) |
| cmake | ✅ WORKS (without special dependencies) |
| cmatrix | ✅ WORKS (without special dependencies) |
| coreutils | ✅ WORKS (without special dependencies) |
| cpio | ✅ WORKS (without special dependencies) |
| c-ray | ✅ WORKS (without special dependencies) |
| curl | ✅ WORKS (without special dependencies) |
| dash | ✅ WORKS (without special dependencies) |
| dialog | ✅ WORKS (without special dependencies) |
| diffutils | ✅ WORKS (without special dependencies) |
| dmidecode | ✅ WORKS (without special dependencies) |
| doom | ✅ WORKS (without special dependencies) |
| dosfstools | ✅ WORKS (without special dependencies) |
| double-conversion | ✅ WORKS (without special dependencies) |
| dropbear | ✅ WORKS (without special dependencies) |
| dtc | ✅ WORKS (without special dependencies) |
| e2fsprogs | ✅ WORKS (without special dependencies) |
| edid-decode | ✅ WORKS (without special dependencies) |
| emu2 | ✅ WORKS (without special dependencies) |
| expat | ✅ WORKS (without special dependencies) |
| figlet | ✅ WORKS (without special dependencies) |
| findutils | ✅ WORKS (without special dependencies) |
| fio | ✅ WORKS (without special dependencies) |
| flac | ✅ WORKS (without special dependencies) |
| flatbuffers | ✅ WORKS (without special dependencies) |
| flex | ✅ WORKS (without special dependencies) |
| freetype | ✅ WORKS (without special dependencies) |
| gawk | ✅ WORKS (without special dependencies) |
| gcc | ✅ WORKS (without special dependencies) |
| gdb | ✅ WORKS (without special dependencies) |
| genemu | ✅ WORKS (without special dependencies) |
| genext2fs | ✅ WORKS (without special dependencies) |
| gettext | ✅ WORKS (without special dependencies) |
| glm | ✅ WORKS (without special dependencies) |
| glu | ✅ WORKS (without special dependencies) |
| gmp | ✅ WORKS (without special dependencies) |
| gperf | ✅ WORKS (without special dependencies) |
| grepcidr | ✅ WORKS (without special dependencies) |
| grep | ✅ WORKS (without special dependencies) |
| gsl | ✅ WORKS (without special dependencies) |
| gzip | ✅ WORKS (without special dependencies) |
| harfbuzz | ✅ WORKS (without special dependencies) |
| hatari | ✅ WORKS (without special dependencies) |
| hexedit | ✅ WORKS (without special dependencies) |
| imgcat | ✅ WORKS (without special dependencies) |
| indent | ✅ WORKS (without special dependencies) |
| isl | ✅ WORKS (without special dependencies) |
| ja2 | ✅ WORKS (without special dependencies) |
| joe | ✅ WORKS (without special dependencies) |
| jot | ✅ WORKS (without special dependencies) |
| kakoune | ✅ WORKS (without special dependencies) |
| klong | ✅ WORKS (without special dependencies) |
| less | ✅ WORKS (without special dependencies) |
| libarchive | ✅ WORKS (without special dependencies) |
| libatomic_ops | ✅ WORKS (without special dependencies) |
| libexpat | ✅ WORKS (without special dependencies) |
| libffi | ✅ WORKS (without special dependencies) |
| libfftw3f | ✅ WORKS (without special dependencies) |
| libgcrypt | ✅ WORKS (without special dependencies) |
| libgd | ✅ WORKS (without special dependencies) |
| libgpg-error | ✅ WORKS (without special dependencies) |
| libiconv | ✅ WORKS (without special dependencies) |
| libicu | ✅ WORKS (without special dependencies) |
| libjpeg | ✅ WORKS (without special dependencies) |
| libmad | ✅ WORKS (without special dependencies) |
| libmikmod | ✅ WORKS (without special dependencies) |
| libmodplug | ✅ WORKS (without special dependencies) |
| libmpeg2 | ✅ WORKS (without special dependencies) |
| libmpg123 | ✅ WORKS (without special dependencies) |
| libogg | ✅ WORKS (without special dependencies) |
| liboggz | ✅ WORKS (without special dependencies) |
| libopenal | ✅ WORKS (without special dependencies) |
| libphysfs | ✅ WORKS (without special dependencies) |
| libpng | ✅ WORKS (without special dependencies) |
| libpuffy | ✅ WORKS (without special dependencies) |
| libsixel | ✅ WORKS (without special dependencies) |
| libsodium | ✅ WORKS (without special dependencies) |
| libssh2 | ✅ WORKS (without special dependencies) |
| libtheora | ✅ WORKS (without special dependencies) |
| libtiff | ✅ WORKS (without special dependencies) |
| libtool | ✅ WORKS (without special dependencies) |
| libunistring | ✅ WORKS (without special dependencies) |
| libuuid | ✅ WORKS (without special dependencies) |
| libuv | ✅ WORKS (without special dependencies) |
| libvorbis | ✅ WORKS (without special dependencies) |
| libxml2 | ✅ WORKS (without special dependencies) |
| libyaml | ✅ WORKS (without special dependencies) |
| libzip | ✅ WORKS (without special dependencies) |
| links | ✅ WORKS (without special dependencies) |
| luajit | ✅ WORKS (without special dependencies) |
| lua | ✅ WORKS (without special dependencies) |
| lz4 | ✅ WORKS (without special dependencies) |
| lzop | ✅ WORKS (without special dependencies) |
| lzo | ✅ WORKS (without special dependencies) |
| m4 | ✅ WORKS (without special dependencies) |
| make | ✅ WORKS (without special dependencies) |
| mandoc | ✅ WORKS (without special dependencies) |
| mawk | ✅ WORKS (without special dependencies) |
| mbedtls | ✅ WORKS (without special dependencies) |
| md4c | ✅ WORKS (without special dependencies) |
| mednafen | ✅ WORKS (without special dependencies) |
| mgba | ✅ WORKS (without special dependencies) |
| milkytracker | ✅ WORKS (without special dependencies) |
| mpc | ✅ WORKS (without special dependencies) |
| mpfr | ✅ WORKS (without special dependencies) |
| mrsh | ✅ WORKS (without special dependencies) |
| nano | ✅ WORKS (without special dependencies) |
| nasm | ✅ WORKS (without special dependencies) |
| ncdu | ✅ WORKS (without special dependencies) |
| ncurses | ✅ WORKS (without special dependencies) |
| nlohmann-json | ✅ WORKS (without special dependencies) |
| npiet | ✅ WORKS (without special dependencies) |
| npth | ✅ WORKS (without special dependencies) |
| nyancat | ✅ WORKS (without special dependencies) |
| oksh | ✅ WORKS (without special dependencies) |
| openssh | ✅ WORKS (without special dependencies) |
| openssl | ✅ WORKS (without special dependencies) |
| openttd-opengfx | ✅ WORKS (without special dependencies) |
| openttd-opensfx | ✅ WORKS (without special dependencies) |
| openttd | ✅ WORKS (without special dependencies) |
| opentyrian | ✅ WORKS (without special dependencies) |
| optipng | ✅ WORKS (without special dependencies) |
| patch | ✅ WORKS (without special dependencies) |
| pcre2 | ✅ WORKS (without special dependencies) |
| pcre | ✅ WORKS (without special dependencies) |
| pfetch | ✅ WORKS (without special dependencies) |
| pixman | ✅ WORKS (without special dependencies) |
| pkgconf | ✅ WORKS (without special dependencies) |
| potrace | ✅ WORKS (without special dependencies) |
| printf | ✅ WORKS (without special dependencies) |
| pt2-clone | ✅ WORKS (without special dependencies) |
| pv | ✅ WORKS (without special dependencies) |
| qoi | ✅ WORKS (without special dependencies) |
| quake2 | ✅ WORKS (without special dependencies) |
| r0 | ✅ WORKS (without special dependencies) |
| radare2 | ✅ WORKS (without special dependencies) |
| readline | ✅ WORKS (without special dependencies) |
| RISCVEmu | ✅ WORKS (without special dependencies) |
| rsync | ✅ WORKS (without special dependencies) |
| sam | ✅ WORKS (without special dependencies) |
| sdl12-compat | ✅ WORKS (without special dependencies) |
| SDL2_gfx | ✅ WORKS (without special dependencies) |
| SDL2-GNUBoy | ✅ WORKS (without special dependencies) |
| SDL2_image | ✅ WORKS (without special dependencies) |
| SDL2_mixer | ✅ WORKS (without special dependencies) |
| SDL2_net | ✅ WORKS (without special dependencies) |
| SDL2_ttf | ✅ WORKS (without special dependencies) |
| SDL2 | ✅ WORKS (without special dependencies) |
| SDL_mixer | ✅ WORKS (without special dependencies) |
| SDLPoP | ✅ WORKS (without special dependencies) |
| sed | ✅ WORKS (without special dependencies) |
| serenity-theming | ✅ WORKS (without special dependencies) |
| sl | ✅ WORKS (without special dependencies) |
| sparsehash | ✅ WORKS (without special dependencies) |
| speexdsp | ✅ WORKS (without special dependencies) |
| sqlite | ✅ WORKS (without special dependencies) |
| stb | ✅ WORKS (without special dependencies) |
| stockfish | ✅ WORKS |
| stress-ng | ✅ WORKS (without special dependencies) |
| Super-Mario | ✅ WORKS (without special dependencies) |
| tar | ✅ WORKS (without special dependencies) |
| tcl | ✅ WORKS (without special dependencies) |
| termcap | ✅ WORKS (without special dependencies) |
| thesilversearcher | ✅ WORKS (without special dependencies) |
| tig | ✅ WORKS (without special dependencies) |
| timidity | ✅ WORKS (without special dependencies) |
| tinycc | ✅ WORKS (without special dependencies) |
| tinyscheme | ✅ WORKS (without special dependencies) |
| tree | ✅ WORKS (without special dependencies) |
| tr | ✅ WORKS (without special dependencies) |
| tuxracer | ✅ WORKS (without special dependencies) |
| vim | ✅ WORKS (without special dependencies) |
| vitetris | ✅ WORKS (without special dependencies) |
| vttest | ✅ WORKS (without special dependencies) |
| wget | ✅ WORKS (without special dependencies) |
| which | ✅ WORKS (without special dependencies) |
| wireguard-tools | ✅ WORKS (without special dependencies) |
| x265 | ✅ WORKS (without special dependencies) |
| xz | ✅ WORKS (without special dependencies) |
| yasm | ✅ WORKS (without special dependencies) |
| zlib | ✅ WORKS (without special dependencies) |
| zsh | ✅ WORKS (without special dependencies) |
| zstd | ✅ WORKS (without special dependencies) |

</details>

**Comment by circl-lastname** [comment]
Powdertoy is broken on some distros where pkgconf is used instead of pkg-config

**Comment by BenWiederhake** [comment]
Well, the "powdertoy" port seems to works as far as I can see, so I don't really understand what you mean?

**Comment by circl-lastname** [comment]
> Well, the "powdertoy" port seems to works as far as I can see, so I don't really understand what you mean?
> 
> EDIT: And of course, the answer is "patch it until it works".

The problem is it *builds* with pkg-config and doesn't build with pkgconf, I don't know how to fix it and I don't know how to respond to the owner on my issue (pkgconf/pkgconf#251)

**Comment by timschumi** [comment]
I don't have anything on the actual topic of the issue yet, but could we move the working ports into a `<details>` section? That way one doesn't have to scroll _that_ far to reach the comments. :^)

**Comment by circl-lastname** [comment]
The issue which occurs for powdertoy (pulling in host headers on systems with pkgconf) also occurs with glib pulling in host libc headers (!!)

**Comment by EWouters** [comment]
I got a different build error for OpenRTC2, but the latest release does build for me on macOS (aarch64). Please check if you still get the same error with https://github.com/SerenityOS/serenity/pull/18377.

**Comment by supercomputer7** [comment]
Pardon my misunderstanding of this, but what do you mean that `file` works but needs the EXACT SAME version installed? did you try a previous version and it didn't work?

**Comment by supercomputer7** [comment]
> > Pardon my misunderstanding of this, but what do you mean that `file` works but needs the EXACT SAME version installed? did you try a previous version and it didn't work?
> 
> I had the scenario that I had `file` 5.44 installed, and when I first ran these tests, the Port still had version 5.43. Trying to install the port of `file` 5.43 aborted compilation with an error message saying something about requiring that the host has the exact same version as the target when cross-compiling. I'll try to recreate the problem, and if I'm successful I'll open an issue, if you'd like?

Sounds good to me, if you can reproduce this.

**Comment by BenWiederhake** [comment]
Already did :P
https://github.com/SerenityOS/serenity/issues/18415

**Comment by fdellwing** [comment]
Taskwarrior builds and runs here:

![image](https://user-images.githubusercontent.com/22813377/234533153-d985030a-3d06-4487-bd23-b9ca0766d339.png)

So we have some unknown host dependency, probably to `gettext`?

**Comment by BenWiederhake** [comment]
- openjdk: I ran `./package.sh` and it worked. I didn't try out all 285 ports. I'll update the table with that issue, thanks!
- lrzip: I ran `./package.sh` and it installs. Yay!
- taskwarrior: I can confirm that with all other ports installed, it successfully builds and installs. Ping me in the PR that fixes the missing dependency :D. Nitpick: It looks like the build step for task warrior is single-threaded, can I give you bonus-points for building with `make -j $(nproc)`? :)

@fdellwing

**Comment by fdellwing** [comment]
I will try to get it to fail with that error and than see what is needed to fix it 👍

**Comment by BenWiederhake** [comment]
I can't reproduce the problem with taskwarrior anymore, and update the table accordingly. No idea what changed o.O

**Comment by fdellwing** [comment]
I dont think `opentyrian-data` port is broken, it is just a port you should not install standalone. It provides *data* for the `opentyrian` port. There has to be a better solution for this, but I can't think of one at the moment.

**Comment by fdellwing** [comment]
`gnuplot` builds for me, from the error description I would have though about `libpng` and `libiconv` dependencies which we both have ports of. But it builds fine without those.

**Comment by BenWiederhake** [comment]
I just checked all of them, and indeed, gnuplot magically works again, despite not being touched. Same with gltron and SDL_sound. I'm confused.

**Comment by moormaster** [comment]
I noticed some weird behaviour with the backward-cpp port.

After doing a
```
$ Meta/serenity.sh delete
$ Meta/serenity.sh build
$ pushd Ports/backward-cpp; ./package.sh; popd
```

The build fails with error messages
```
=> Building backward-cpp...
[backward-cpp/build] + make -j24
[backward-cpp/build] [ 21%] Built target backward_object
[backward-cpp/build] [ 28%] Built target backward
[backward-cpp/build] [ 28%] Built target test_main
[backward-cpp/build] [ 42%] Linking CXX executable test_rectrace
[backward-cpp/build] [ 50%] Linking CXX executable test_stacktrace
[backward-cpp/build] [ 57%] Linking CXX executable test_select_signals
[backward-cpp/build] [ 64%] Built target test_test
[backward-cpp/build] [ 71%] Linking CXX executable test_suicide
[backward-cpp/build] /home/moormaster/tmp/git/serenity/Toolchain/Local/x86_64/lib/gcc/x86_64-pc-serenity/13.1.0/../../../../x86_64-pc-serenity/bin/ld: /home/moormaster/tmp/git/serenity/Toolchain/Local/x86_64/lib/gcc/x86_64-pc-serenity/13.1.0/../../../../x86_64-pc-serenity/bin/ld: /home/moormaster/tmp/git/serenity/Toolchain/Local/x86_64/lib/gcc/x86_64-pc-serenity/13.1.0/../../../../x86_64-pc-serenity/bin/ld: /home/moormaster/tmp/git/serenity/Toolchain/Local/x86_64/lib/gcc/x86_64-pc-serenity/13.1.0/../../../../x86_64-pc-serenity/bin/ld: /home/moormaster/tmp/git/serenity/Build/x86_64/Root/usr/local/lib/libbfd.a(elfxx-x86.o): in function `/home/moormaster/tmp/git/serenity/Build/x86_64/Root/usr/local/lib/libbfd.a(elfxx-x86.o)_bfd_x86_elf_write_sframe_plt: in function `':
[backward-cpp/build] /home/moormaster/tmp/git/serenity/Build/x86_64/Ports/binutils/binutils-2.40/bfd/elfxx-x86.c:1975: undefined reference to `sframe_encoder_write_bfd_x86_elf_write_sframe_plt':
[backward-cpp/build] '
[backward-cpp/build] /home/moormaster/tmp/git/serenity/Build/x86_64/Ports/binutils/binutils-2.40/bfd/elfxx-x86.c:1975: undefined reference to `/home/moormaster/tmp/git/serenity/Toolchain/Local/x86_64/lib/gcc/x86_64-pc-serenity/13.1.0/../../../../x86_64-pc-serenity/bin/ldsframe_encoder_write: '
[backward-cpp/build] /home/moormaster/tmp/git/serenity/Toolchain/Local/x86_64/lib/gcc/x86_64-pc-serenity/13.1.0/../../../../x86_64-pc-serenity/bin/ld/home/moormaster/tmp/git/serenity/Build/x86_64/Ports/binutils/binutils-2.40/bfd/elfxx-x86.c:: 1981: undefined reference to `sframe_encoder_free'
...
```

But if I build the gdb Port first
```
$ Meta/serenity.sh delete
$ Meta/serenity.sh build
$ pushd Ports/gdb; ./package.sh; popd
$ pushd Ports/backward-cpp; ./package.sh; popd
```
the build of backward-cpp suddenly succeeds. Is it missing a dependency in its package.sh ?

**Comment by BenWiederhake** [comment]
That is very much possible! I would like to keep this issue high-level, feel free to create a new issue about backward-cpp in particular, or even better: Fix it :D

**Comment by fdellwing** [comment]
`nethack` and `boost` should work right now.

**Comment by tajmorton** [comment]
@BenWiederhake 

> Port | Status
> -- | --
> alpine | BROKEN: libtool version mismatch???


Any details on the alpine libtool error you encountered? I successfully built alpine on c4656a70c10d40f238c78d6af5e052a4bf38147d today (Ubuntu 22.04 host).

**Comment by seal331** [comment]
Thanks to whoever fixed the taskwarrior port (either that PR or by accident fixing some other code), next time if there's an issue with ports I committed please ping me

**Comment by BenWiederhake** [comment]
@seal331 I think that's what the file `.github/CODEOWNERS` is for :)

**Comment by timschumi** [comment]
> I think that's what the file .github/CODEOWNERS is for :)

That file sadly only works for maintainers. :^(

**Comment by gloof11** [comment]
I was able to install nesalizer on my system just fine. However, there is an audio buffer underflow issue that warrants being looked at.

**Comment by gloof11** [comment]
I was able to build nesalizer and install it to Serenity. However, the audio is really choppy. I'm currently looking into if its a bug, or just that my Serenity build doesn't have enough resources.

**Comment by aggregate1166877** [comment]
I'll jump on this bandwagon and add one to the list if I may :P

[jfduke3d](https://github.com/SerenityOS/serenity/tree/master/Ports/jfduke3d) fails when running `./package.sh`:

```
=> Patching jfduke3d...
[jfduke3d/pre_patch] /data/serenity/Build/x86_64/Ports/jfduke3d/jfduke3d-41cd46bc00633e7457d07d88c8add9f99a7d9d41 /data/serenity/Build/x86_64/Ports/jfduke3d
[jfduke3d/pre_patch] /data/serenity/Build/x86_64/Ports/jfduke3d
[jfduke3d/configure] This port does not use a configure script. Skipping configure step.
=> Building jfduke3d...
[jfduke3d/build] + make USE_OPENGL=0 WITHOUT_GTK=1 USE_POLYMOST=1 SDL2CONFIG=/data/serenity/Build/x86_64/Root/usr/local/bin/sdl2-config
[jfduke3d/build] x86_64-pc-serenity-gcc  -Isrc -Ijfbuild/include -Ijfmact -Ijfaudiolib/include -DRENDERTYPESDL=1 -DUSE_POLYMOST=1 -fomit-frame-pointer -O1 -g -W -Wall -fno-strict-aliasing -std=c99  -I/data/serenity/Build/x86_64/Root/usr/local/include/SDL2 -D_REENTRANT -c src/game.c -o src/game.o
[jfduke3d/build] In file included from jfbuild/include/build.h:22,
[jfduke3d/build]                  from src/duke3d.h:32,
[jfduke3d/build]                  from src/game.c:28:
[jfduke3d/build] jfbuild/include/compat.h:147:3: error: #error Unknown endianness
[jfduke3d/build]   147 | # error Unknown endianness
[jfduke3d/build]       |   ^~~~~
[jfduke3d/build] jfbuild/include/compat.h: In function 'B_SWAPFLOAT':
[jfduke3d/build] jfbuild/include/compat.h:169:11: warning: implicit declaration of function 'B_SWAP32' [-Wimplicit-function-declaration]
[jfduke3d/build]   169 |     x.i = B_SWAP32(x.i);
[jfduke3d/build]       |           ^~~~~~~~
[jfduke3d/build] make: *** [Makefile:183: src/game.o] Error 1
Error in step jfduke3d/build (status=2)
```

AMD Ryzen 7 1700, Ubuntu 24.04 inside schroot.

**Comment by BenWiederhake** [comment]
You might wanna re-run all Ports and create a new issue; this one is outdated.

**Comment by aggregate1166877** [comment]
> You might wanna re-run all Ports and create a new issue; this one is outdated.

Noob question - is there an easy way to do them all at once? Currently the only method I'm aware of is the manually `cd` into each directory and run each `package.sh` (or generate a script to do that for me).

**Comment by circl-lastname** [comment]
Try https://github.com/SerenityOS/serenity/blob/master/Ports/build_all.sh

**Comment by BenWiederhake** [comment]
I also suggest doing this on a minimal VM; this way, hidden dependencies might become more obvious.

**Comment by fonetyka** [comment]
```
[libmpg123/build] x86_64-pc-serenity-gcc -DHAVE_CONFIG_H -I. -I./src  -DPKGLIBDIR="\"/usr/local/lib/mpg123\""  -I./src -I./src/compat -I./src/libmpg123 -I./src/libout123 -I./src/libmpg123 -I./src/libsyn123 -I./src/libout123 -DOPT_MULTI -DOPT_X86_64 -DOPT_GENERIC -DOPT_GENERIC_DITHER -DREAL_IS_FLOAT -DOPT_AVX   -O2 -fomit-frame-pointer -funroll-all-loops -finline-functions -ffast-math  -g -O2 -MT src/term_posix.o -MD -MP -MF $depbase.Tpo -c -o src/term_posix.o src/term_posix.c &&\
[libmpg123/build] mv -f $depbase.Tpo $depbase.Po
[libmpg123/build] src/streamdump.c: In function 'dump_setup':
[libmpg123/build] src/streamdump.c:691:17: error: too many arguments to function 'dump_close'; expected 0, have 1
[libmpg123/build]   691 |                 dump_close(sd);
[libmpg123/build]       |                 ^~~~~~~~~~ ~~
[libmpg123/build] In file included from src/streamdump.c:16:
[libmpg123/build] src/streamdump.h:53:6: note: declared here
[libmpg123/build]    53 | void dump_close();
[libmpg123/build]       |      ^~~~~~~~~~
[libmpg123/build] make: *** [Makefile:4082: src/streamdump.o] Error 1
[libmpg123/build] make: *** Waiting for unfinished jobs....
```

**Comment by BenWiederhake** [comment]
Given that the table is hopelessly outdated and I don't wanna receive more spam, I'm closing this issue. Feel free to open a new issue to track the current state of things.
