### PR TITLE
js: Fix "error: ‘%s’ directive argument is null" (Lagom build)

### PR DESCRIPTION
**Pull request by linusg**
Lagom build of js was broken for me after https://github.com/SerenityOS/serenity/pull/2098 was merged. Seems to be fine for other people's host compilers (source: @awesomekling on IRC)

```
serenity/Userland/js.cpp: In member function ‘virtual JS::Value ReplConsoleClient::trace()’:
serenity/Userland/js.cpp:443:19: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
  443 |             printf(" -> %s\n", function_name.characters());
      |             ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[3]: *** [CMakeFiles/js.dir/build.make:83: CMakeFiles/js.dir/serenity/Userland/js.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:131: CMakeFiles/js.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:138: CMakeFiles/js.dir/rule] Error 2
make: *** [Makefile:151: js] Error 2
```

Now works on my machine (:tm:) again (Fedora 32, `gcc` 10.0.1)

### CODE REVIEW

**Comment by linusg** [comment]
no kidding, https://github.com/SerenityOS/serenity/commit/5c12f3fef045b5c45b4a9e7fb9a9949a9b5d6101 already fixed it!
