### PR TITLE
More ports updates

### PR DESCRIPTION
**Pull request by linusg**
Just a few random ones.

### CODE REVIEW

File: Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch [hunk 1]
```diff
@@ -58,20 +58,29 @@ Co-Authored-By: sdomi <ja@sdomi.pl>
...
+index 30ff00adf93878c328f534ca6a3acdd082d8f1dd..20a0d6bf23a2b665265c63fdcbf6958a6f2ae94d 100644
 --- a/CMakeLists.txt
 +++ b/CMakeLists.txt
-@@ -32,6 +32,9 @@ set(PKGCONFIG_DEPENDS)
+@@ -6,7 +6,7 @@ endif()
+ set(CMAKE_POLICY_DEFAULT_CMP0091 NEW)
+ 
+ cmake_minimum_required(VERSION 3.0.0...3.10)
+-project(SDL2 C)
++project(SDL2 C CXX)
```
Comment (linusg) [inline Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch:69]: This stopped building our added cpp files and led to a linker error, not sure how that worked before.

File: Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch [hunk 2]
```diff
@@ -141,7 +150,7 @@ index 815665364785ca6e6eb679ed345ff5581ffe235a..9c52ab96fc0694c7400092ef5c513d56
 +
 +    set(CMAKE_CXX_FLAGS "-std=c++23 -fno-exceptions ${CMAKE_CXX_FLAGS}")
 +    file(GLOB SERENITY_SOURCES ${SDL2_SOURCE_DIR}/src/video/serenity/*.cpp ${SDL2_SOURCE_DIR}/src/audio/serenity/*.cpp)
-+    set(SOURCE_FILES ${SOURCE_FILES} ${SERENITY_SOURCES})
++    list(APPEND SOURCE_FILES ${SERENITY_SOURCES})
```
Comment (linusg) [inline Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch:153]: Functionally equivalent, using the same mechanism as the surrounding blocks now.

File: Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch [hunk 3]
```diff
@@ -473,20 +482,20 @@ index 344efec489de223f4dd1895251ccb1baa2a0bd91..8428261a419141be04fab94f6f8885fe
...
+index 01023753c6e49967e33d4f402e2272040a31190d..fcf6e50737387094646101d30b81c4a30c625eb9 100644
 --- a/src/video/SDL_video.c
 +++ b/src/video/SDL_video.c
-@@ -66,6 +66,9 @@
+@@ -72,6 +72,9 @@
  
  /* Available video drivers */
  static VideoBootStrap *bootstrap[] = {
-+#if SDL_VIDEO_DRIVER_SERENITY
++#ifdef SDL_VIDEO_DRIVER_SERENITY
```
Comment (linusg) [inline Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch:492]: Small tweak for consistency, other ifdefs below do the same.

File: Ports/curl/package.sh [hunk 4]
```diff
@@ -19,6 +19,7 @@ configure() {
         -S "curl-${version}" \
         -B curl-build \
         -DCMAKE_TOOLCHAIN_FILE="${SERENITY_BUILD_DIR}/CMakeToolchain.txt" \
+        -DCURL_USE_LIBPSL='OFF' \
```
Comment (linusg) [inline Ports/curl/package.sh:22]: See commit message.

File: Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch (hunk 1 above)
Comment (spholz) [reply Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch:69]: Weird, SDL2 builds on my system just fine. Maybe something different in your build environment leaks into the port build?

What is the linker error?

Comment (linusg) [reply Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch:69]: SDL2 2.30.5 (master) builds fine with no changes, 2.32.0 (this PR) gives me this without the `CXX` addition:

```
...
[SDL2/build] [ 99%] Linking C shared library libSDL2-2.0.so
[SDL2/build] [100%] Linking C static library libSDL2.a
[SDL2/build] /home/linus/Dev/serenity/Toolchain/Local/x86_64/lib/gcc/x86_64-pc-serenity/13.2.0/../../../../x86_64-pc-serenity/bin/ld: CMakeFiles/SDL2.dir/src/audio/SDL_audio.c.o:(.data.rel.ro+0x0): undefined reference to `SERENITYAUDIO_bootstrap'
[SDL2/build] /home/linus/Dev/serenity/Toolchain/Local/x86_64/lib/gcc/x86_64-pc-serenity/13.2.0/../../../../x86_64-pc-serenity/bin/ld: CMakeFiles/SDL2.dir/src/video/SDL_video.c.o:(.data.rel+0x0): undefined reference to `SERENITYVIDEO_bootstrap'
[SDL2/build] collect2: error: ld returned 1 exit status
[SDL2/build] make[2]: *** [CMakeFiles/SDL2.dir/build.make:2804: libSDL2-2.0.so.0.3200.0] Error 1
[SDL2/build] make[1]: *** [CMakeFiles/Makefile2:162: CMakeFiles/SDL2.dir/all] Error 2
[SDL2/build] make[1]: *** Waiting for unfinished jobs....
[SDL2/build] [100%] Built target SDL2-static
[SDL2/build] make: *** [Makefile:136: all] Error 2
```

All `Building CXX object` lines are absent.

Comment (spholz) [reply Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch:69]: Oh sorry, I misread your comment.
I'm not sure why it wouldn't build our C++ sources though.
Maybe `enable_language(CXX)` in sdlchecks.cmake helps? The android target seems to already do that in that file.

Comment (linusg) [reply Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch:69]: I mean, it works now. Is there anything wrong with patching `project()` to receive the right list of languages?

Comment (spholz) [reply Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch:69]: Well yeah, I guess it's fine
