### PR TITLE
Ports: Add missing dependency on ncurses to bash

### PR DESCRIPTION
**Pull request by butter1125**

### CODE REVIEW

**Comment by timschumi** [comment]
I built `bash` countless times and it always seems to have worked just fine without `ncurses`. Are we sure that this is necessary?

**Comment by butter1125** [comment]
Maybe a solution would be to install `ncurses`. Then at least this problem would go away.

**Comment by timschumi** [comment]
Finally got around to bisecting this, turns out it is caused by c1a4a0e1afb2cd71c132b110e8e151ee6185dc2e ("LibC: Remove our ad-hoc termcap implementation"). This probably caused some confusion in the configure scripts as to which implementation(s) should be enabled in replacement.

Apologies for the confusion, feel free to reopen the PR. Although, it might be more appropriate to include `readline` as the dependency instead.

**Comment by timschumi** [comment]
For posterity, this is the relevant build error:

```
[bash/build] x86_64-pc-serenity-gcc -L./builtins -L./lib/readline -L./lib/readline -L./lib/glob -L./lib/tilde  -L./lib/sh  -L./lib/termcap  -g -O2   -o bash shell.o eval.o y.tab.o general.o make_cmd.o print_cmd.o  dispose_cmd.o execute_cmd.o variables.o copy_cmd.o error.o expr.o flags.o jobs.o subst.o hashcmd.o hashlib.o mailcheck.o trap.o input.o unwind_prot.o pathexp.o sig.o test.o version.o alias.o array.o arrayfunc.o assoc.o braces.o bracecomp.o bashhist.o bashline.o  list.o stringlib.o locale.o findcmd.o redir.o pcomplete.o pcomplib.o syntax.o xmalloc.o signames.o -lbuiltins -lglob -lsh -lreadline -lhistory ./lib/termcap/libtermcap.a -ltilde     -ldl 
[bash/build] /serenity/Toolchain/Local/x86_64/lib/gcc/x86_64-pc-serenity/13.2.0/../../../../x86_64-pc-serenity/bin/ld: ./lib/termcap/libtermcap.a(termcap.o):/serenity/Build/x86_64/Ports/bash/bash-5.2.32/lib/termcap/termcap.c:298: multiple definition of `PC'; ./lib/readline/libreadline.a(terminal.o):/serenity/Build/x86_64/Ports/bash/bash-5.2.32/lib/readline/terminal.c:109: first defined here
[bash/build] /serenity/Toolchain/Local/x86_64/lib/gcc/x86_64-pc-serenity/13.2.0/../../../../x86_64-pc-serenity/bin/ld: ./lib/termcap/libtermcap.a(tparam.o):/serenity/Build/x86_64/Ports/bash/bash-5.2.32/lib/termcap/tparam.c:126: multiple definition of `BC'; ./lib/readline/libreadline.a(terminal.o):/serenity/Build/x86_64/Ports/bash/bash-5.2.32/lib/readline/terminal.c:109: first defined here
[bash/build] /serenity/Toolchain/Local/x86_64/lib/gcc/x86_64-pc-serenity/13.2.0/../../../../x86_64-pc-serenity/bin/ld: ./lib/termcap/libtermcap.a(tparam.o):/serenity/Build/x86_64/Ports/bash/bash-5.2.32/lib/termcap/tparam.c:127: multiple definition of `UP'; ./lib/readline/libreadline.a(terminal.o):/serenity/Build/x86_64/Ports/bash/bash-5.2.32/lib/readline/terminal.c:109: first defined here
```

**Comment by butter1125** [comment]
I agree, including `readline` as the dependency would be better. Sorry for the trouble.

**Comment by butter1125** [comment]
But I can't reopen this closed pull request so I'll open a new one.
